src/ResumeBuilderTeam2/CVBuilder.web/Areas/Users/Models/CVBuilderDTO.cs
using CVBuilder.Domain.CVEntites.BaseEntites;
using CVBuilder.Domain.CVEntites.Sections;

namespace CVBuilder.Web.Areas.Users.Models
{
    public class References
    {
        public string Designation { get; set; }
        public string Name { get; set; }
    }
    public class CVBuilderDTO
    {
        public string name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public ProfessionalSummarySection ProfessionalSummary { get; set; }
        public List<string> Skills { get; set; }
        public List<WorkExperience> WorkExperiences { get; set; }

        public List<Project>? Projects { get; set; }
        public List<ProfessionalTrainingSection> Trainning { get; set; }

        public List<Education> Education { get; set; }

        public List<References> References { get; set; }

       



        //public int Id { get; set; }
        //public string FullName { get; set; }
        //public string Email { get; set; }
        //public string ContactNumber { get; set; }
        //public string Skype { get; set; }
        //public string LinkedIn { get; set; }
        //public string ResidentialAddress { get; set; }
        //public string ProfessionalSummary { get; set; }

        //// Navigation properties
        //public ICollection<LanguageSkill> LanguageSkills { get; set; }
        //public ICollection<WorkExperience> WorkExperiences { get; set; }
        //public ICollection<IndustrialProject> IndustrialProjects { get; set; }
        //public ICollection<Training> Trainings { get; set; }
        //public ICollection<Education> Educations { get; set; }
        //public ICollection<Reference> References { get; set; }

    }
}

src/ResumeBuilderTeam2/CVBuilder.web/Areas/Users/Models/ResumeBuilderVM.cs
namespace CVBuilder.Web.Areas.Users.Models
{
    public class ResumeBuilderVM
    {
    }
}

src/ResumeBuilderTeam2/CVBuilder.web/Areas/Users/Controllers/CoverLetterController.cs
using Autofac;
using Crud.Persistance.Features.Membership;
using CVBuilder.Domain.Entities;
using CVBuilder.Web.Areas.Users.Models;
using CVBuilder.Web.Models;
using CVBuilder.Web.Utilities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;


namespace CVBuilder.Web.Areas.Users.Controllers
{
    [Area("Users")]
    public class CoverLetterController : Controller
    {
        private readonly IHostingEnvironment _environment;
        ILifetimeScope _scope;

        private readonly UserManager<ApplicationUser> _userManager;

        public CoverLetterController(IHostingEnvironment hostingEnvironment, ILifetimeScope scope,
            UserManager<ApplicationUser> userManager)
        {
            _environment = hostingEnvironment;
            _scope = scope;
            _userManager = userManager;

        }

        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(HttpContext.User);


            var model = _scope.Resolve<CoverLetterDataModel>();
            model.Load(new Guid(userId));
            return View(model);

        }




        public IActionResult Create()
        {
            var model = _scope.Resolve<CoverLetterCreateModel>();

            return View(model);
        }
       
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Create(CoverLetterCreateModel model)
        {

            model.ResolveDependency(_scope);

            if (ModelState.IsValid)
            {
                try
                {


                    var userId = _userManager.GetUserId(HttpContext.User);

                    //var cvtemplate = await _resumeFactory.PrepareResume(CVData);
                    CommonClass.Uid = userId;
                    model.CreateCoverLetter();
                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = "Successfully added a new Cover Letter.",
                        Type = ResponseTypes.Success
                    });
                    return RedirectToAction("Index");
                }
                catch (DuplicateNameException ex)
                {

                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = ex.Message,
                        Type = ResponseTypes.Danger
                    });
                }
                catch (Exception e)
                {


                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = "There was a problem in creating Cover Letter.",
                        Type = ResponseTypes.Danger
                    });
                }
            }

            return View(model);
        }


        //delete
        public async Task<JsonResult> CoverLetterDelete(int id, Guid userId)
        {

            //var model = 
            var model = _scope.Resolve<CoverLetterDeleteModel>();
            model.ResolveDependency(_scope);
            model.DeleteCoverLetter(id, userId);
            return new JsonResult("Delete Successful");
        }

        //update
        public async Task<JsonResult> CoverLetterUpdate(UserCoverLetter userCoverLetter)
        {

            //var model = 
            var model = _scope.Resolve<CoverLetterUpdateModel>();
            model.ResolveDependency(_scope);
            model.UserCoverLetter = userCoverLetter;
            model.UpdateCoverLetter();
            return new JsonResult("Update Successful");

        }
    }
}

src/ResumeBuilderTeam2/CVBuilder.web/Areas/Users/Controllers/ResumeController.cs
using Autofac;
using Crud.Persistance.Features.Membership;
using CVBuilder.Domain.CVEntites;
using CVBuilder.Domain.Entities;
using CVBuilder.Web.Areas.Admin.Models.ResumeTemplateModel;
using CVBuilder.Web.Areas.Users.Factory;
using CVBuilder.Web.Areas.Users.Models;
using CVBuilder.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Org.BouncyCastle.Ocsp;
using System.Collections;
using System.Xml.Linq;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace CVBuilder.Web.Areas.Users.Controllers
{
	[Area("Users")]
	public class ResumeController : Controller
	{
		//  [Authorize]
		private readonly IHostingEnvironment _environment;
		private readonly IResumeFactory _resumeFactory;
		private readonly ILifetimeScope _scope;
		private readonly UserManager<ApplicationUser> _userManager;
		private  Resume _resumeModel;
		private IList<ResumeTemplate>? _resumetemplates;
		
		public ResumeController(IHostingEnvironment hostingEnvironment, ILifetimeScope scope,
		   IResumeFactory resumeFactory, UserManager<ApplicationUser> userManager)
		{
			_environment = hostingEnvironment;
			_resumeFactory = resumeFactory;
			_scope = scope;
			_userManager = userManager;
           

        }
		public IActionResult ResumeBuilder()
		{
			return View();
		}

		public async Task<IActionResult> EditResumeData()
		{
			var httpCon = HttpContext.Request.QueryString;
			var queryString = QueryHelpers.ParseQuery(httpCon.Value);
			int.TryParse(queryString["tempId"].ToString(), out int tempId);

            var model = await GetResumeByUserAndTempleteId(tempId);
			_resumeModel = model;
            var cvData = model;
			if (cvData != null)
			{
				ViewBag.Project = cvData.Projects;
				ViewBag.Skills = cvData.Skills.SkillsList;
				ViewBag.References = cvData.References;
				ViewBag.ResumeName = cvData.ResumeName;
				ViewBag.Education = cvData.Education;
				ViewBag.Introduction = cvData.Introduction;
				ViewBag.ProfessionalSummary = cvData.ProfessionalSummary;
				ViewBag.ProfessionalTraining = cvData.ProfessionalTraining;
				ViewBag.WorkExperiences = cvData.WorkExperiences;

			}
			return View("edit-template");
		}

		//Need to change action name view resume/cv 
		// it take a resume id 
		// ger al resume info by id with template name or id 
		// return to view page as per template id
		public IActionResult ShowTemplateOne()
		{
			var httpCon = HttpContext.Request.QueryString;
			var queryString = QueryHelpers.ParseQuery(httpCon.Value);
			int.TryParse(queryString["tempId"].ToString(), out int tempId);

            ViewBag.SheareLink = $"https://localhost:7231/Users/Resume/ShowTemplateOne?tempId={tempId}";
            var model = GetResumeByUserAndTempleteId(tempId);
			var cvData = model.Result;
			//List<string> cvTemplate = new List<string>();
			//cvTemplate.Add("templete-two");
			//cvTemplate.Add("template-one");
            var templates = _scope.Resolve<ResumeTemplateListModel>();
            if (cvData != null)
			{
				var resumTempltes = templates.GetResumeTemplates();
                ViewBag.Project = cvData.Projects;
				ViewBag.Skills = cvData.Skills.SkillsList;
				ViewBag.References = cvData.References;
				ViewBag.ResumeName = cvData.ResumeName;
				ViewBag.Education = cvData.Education;
				ViewBag.Introduction = cvData.Introduction;
				ViewBag.ProfessionalSummary = cvData.ProfessionalSummary;
				ViewBag.ProfessionalTraining = cvData.ProfessionalTraining;
				ViewBag.WorkExperiences = cvData.WorkExperiences;
				ViewBag.templates = resumTempltes;
                _resumetemplates = resumTempltes as IList<ResumeTemplate>;
            }
				var defaultTemplate = _resumetemplates.Where(x => x.Id == tempId).FirstOrDefault();
			
			//ChooseTemplate();
            return View(defaultTemplate.TemplateName);
		}

		public async Task<bool> DeleteResumeByTemplateId(int templateId)
		{
			try
			{
				var userId = _userManager.GetUserId(HttpContext.User);
				var model = _scope.Resolve<ResumeCreateModel>();
				var result = await model.GetCVByByUserIdWithTempateId(Guid.Parse(userId), templateId);
				model.DeleteResumeData(result);
				return true;
			}
			catch (Exception ex)
			{
				return false;

			}
		}

		[Authorize]
		public IActionResult Index()
		{
			return View();
		}

		public async Task<Resume> GetResumeByUserAndTempleteId(int tempId)
		{
			var userId = _userManager.GetUserId(HttpContext.User);
			var model = _scope.Resolve<ResumeCreateModel>();
			var result = await model.GetCVByByUserIdWithTempateId(Guid.Parse(userId), tempId);
			return result;
		}
		public async Task<JsonResult> GetCVByUserIdWithTemplateId()
		{
			var param1Value = HttpContext.Request.Query.ContainsKey("tempId");
			var userId = _userManager.GetUserId(HttpContext.User);
			var model = _scope.Resolve<ResumeCreateModel>();
			model.ResolveDependency(_scope);
			//using the model according to sirs model
			var result = await model.GetCVByByUserIdWithTempateId(Guid.Parse(userId), 0); //fully function insertion resume
			return new JsonResult(result);
		}
		// update 
		public async Task<JsonResult> UpdateCVByUserIdAndTemplateId(Resume cVTemplate, ResumeDTO CVData)
		{
			var model = _scope.Resolve<ResumeUpdateModel>();
			model.ResolveDependency(_scope);
			var result = await model.CVUpdateByUserIdAndTemplateId(cVTemplate, CVData);
			return new JsonResult(result);
		}

		//Generate Resume 
		public async Task<JsonResult> CVBuilderAdd(ResumeDTO CVData)
		{
			var queryString = QueryHelpers.ParseQuery(CVData.Url);
			int tempId = 0;
			int.TryParse(queryString["tempId"].ToString(), out tempId);

			//    return
			var model = _scope.Resolve<ResumeCreateModel>();
			model.ResolveDependency(_scope);
			var userId = _userManager.GetUserId(HttpContext.User);

			var existingCVData = await model.GetCVByByUserIdWithTempateId(Guid.Parse(userId), tempId);
			if (existingCVData != null)
			{
				// update CV 
				try
				{

					return new JsonResult("CV all rady exists");
				}
				catch (Exception ex)
				{
					return null;
				}
			}

			try
			{
				var cvtemplate = await _resumeFactory.PrepareResume(CVData);
				cvtemplate.UserId = new Guid(userId);//for testing purpose
				cvtemplate.ResumeTemplteId = tempId;
				//var model = 
				model.CVTemplate = cvtemplate;//using the model according to sirs model
				model.CreateResume(); //fully function insertion resume
				return new JsonResult("Add Successful");

				
			}
			catch (Exception ex)
			{
				return new JsonResult("Some Thing Wrong");

			}
		}


		/// <summary>
		/// 	[Route("/UpdateRemuseData")]
		/// </summary>
		/// <param name="CVData"></param>
		/// <returns></returns>
		[Route("/UpdateRemuseData")]

		public async Task<JsonResult> UpdateRemuseData(ResumeDTO CVData)
		{
			var queryString = QueryHelpers.ParseQuery(CVData.Url);
			int tempId = 0;
			int.TryParse(queryString["tempId"].ToString(), out tempId);
			var model = _scope.Resolve<ResumeCreateModel>();
			model.ResolveDependency(_scope);
			var userId = _userManager.GetUserId(HttpContext.User);

			var existingCVData = await model.GetCVByByUserIdWithTempateId(Guid.Parse(userId), tempId);
			if (existingCVData != null)
			{
				var rr = model.DeleteResumeData(existingCVData);

			}
			try
			{
				var cvtemplate = await _resumeFactory.PrepareResume(CVData);
				cvtemplate.UserId = new Guid(userId);//for testing purpose
				cvtemplate.ResumeTemplteId = tempId;
				//var model = 
				model.CVTemplate = cvtemplate;//using the model according to sirs model
				model.CreateResume(); //fully function insertion resume
				return new JsonResult("Updated Successful");
			}
			catch (Exception ex)
			{
				return new JsonResult("Some Thing Wrong");

			}

		}


		public async Task<JsonResult> ImageUpload()
		{
			string base64 = Request.Form["image"];
			byte[] bytes = Convert.FromBase64String(base64.Split(',')[1]);
			string filePath = Path.Combine(this._environment.WebRootPath, "images", $"{_userManager.GetUserId(HttpContext.User)}.png");
			using (FileStream stream = new FileStream(filePath, FileMode.Create))
			{
				stream.Write(bytes, 0, bytes.Length);
				stream.Flush();
			}
			return new JsonResult($"{_userManager.GetUserId(HttpContext.User)}.png");
		}


		//[HttpGet("/ChangeTemplate/temp")]
		public async Task<IActionResult> ChangeTemplate() {
            var httpCon = HttpContext.Request.QueryString;
            var queryString = QueryHelpers.ParseQuery(httpCon.Value);
            int.TryParse(queryString["tempId"].ToString(), out int tempId);
            int.TryParse(queryString["temp"].ToString(), out int temp);
		   var  templates = _scope.Resolve<ResumeTemplateListModel>().GetResumeTemplates();
			_resumetemplates = templates;
            var userId = _userManager.GetUserId(HttpContext.User);
            var model = _scope.Resolve<ResumeCreateModel>();
            var cvData = await GetResumeByUserAndTempleteId(tempId);
            
            ViewBag.Project = cvData.Projects;
            ViewBag.Skills = cvData.Skills.SkillsList;
            ViewBag.References = cvData.References;
            ViewBag.ResumeName = cvData.ResumeName;
            ViewBag.Education = cvData.Education;
            ViewBag.Introduction = cvData.Introduction;
            ViewBag.ProfessionalSummary = cvData.ProfessionalSummary;
            ViewBag.ProfessionalTraining = cvData.ProfessionalTraining;
            ViewBag.WorkExperiences = cvData.WorkExperiences;
			ViewBag.templates = templates;
            var template = _resumetemplates.Where(x => x.Id == temp).FirstOrDefault();
            return View(template.TemplateName);
		}

	}
}

src/ResumeBuilderTeam2/CVBuilder.web/Areas/Users/Controllers/ResumeTemplateController.cs
using Microsoft.AspNetCore.Mvc;

namespace CVBuilder.Web.Areas.Users.Controllers
{
    [Area("Users")]
    public class ResumeTemplateController : Controller
    {
        public IActionResult Template1()
        {
            return View();
        }
    }
}

src/ResumeBuilderTeam2/CVBuilder.web/Areas/Users/Controllers/UserController.cs
using Autofac;
using Crud.Persistance.Features.Membership;
using CVBuilder.Web.Areas.Admin.Models.ResumeTemplateModel;
using CVBuilder.Web.Areas.Users.Models;
using CVBuilder.Web.Controllers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace CVBuilder.Web.Areas.Users.Controllers
{
    [Area("Users")]
    public class UserController : Controller
	{ 
        private readonly ILifetimeScope _scope;
        private readonly ILogger<UserController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        public readonly ResumeCreateModel _resume;

        public UserController(ILifetimeScope scope, ILogger<UserController> logger,
        UserManager<ApplicationUser> userManager, ResumeCreateModel resume)
        {
            _scope = scope;
            _logger = logger;
            _userManager = userManager;
           _resume = resume;
		}
        public IActionResult Index()
		{
			return View();
		}
        public IActionResult Profile()
        {
            var CV = _resume.GetCV(1);
            var userId = _userManager.GetUserId(HttpContext.User);
           var getAllResumeByUser =   _resume.GetAllResumeByUser(Guid.Parse(userId));
			var user = _userManager.FindByIdAsync(userId);
            ViewBag.user = user.Result;
            ViewBag.Photo = user.Result.ProfilePictureUrl;
            ViewBag.UserAllResume = getAllResumeByUser.Result;

			if (ViewBag.Photo == null)
            {
                ViewBag.Photo = "/images/ProfilePhoto/avatar.png";
			}
                return View();
        }
        public IActionResult ChooseTemplate()
        {
            var model = _scope.Resolve<ResumeTemplateListModel>();
            return View(model);
        }
    }
}

src/ResumeBuilderTeam2/CVBuilder.web/Areas/Users/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

src/ResumeBuilderTeam2/CVBuilder.web/Areas/Users/Views/User/Profile.cshtml
@{
    ViewData["Title"] = "Profile";
}
@section Styles{
	<style>
	body{
    background: #f7f7ff;
    margin-top:150px;
	}
	.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid transparent;
    border-radius: .25rem;
    margin-bottom: 1.5rem;
    box-shadow: 0 2px 6px 0 rgb(218 218 253 / 65%), 0 2px 6px 0 rgb(206 206 238 / 54%);
	}
	.me-2 {
    margin-right: .5rem!important;
	}

	.card-body h6{
		line-height:2.5;
	}
	</style>
}

<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="card">
					<div class="card-body">
						<div class="d-flex flex-column align-items-center text-center">
						<img src="@ViewBag.Photo" class="rounded-circle p-1 bg-primary" width="125" height="125">
							<div class="mt-3">
							<h4>@ViewBag.user.FirstName @ViewBag.user.LastName</h4>
								<p class="text-secondary mb-1">Full Stack Developer</p>
								<p class="text-muted font-size-sm">@ViewBag.user.Address</p>								
							</div>
						</div>
						<hr class="my-4">
						<ul class="list-group list-group-flush">
							<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
								<h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe me-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
							<span class="text-secondary"><a href="#">https://team2.com</a></span>
							</li>
							<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
								<h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github me-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
							<span class="text-secondary"><a href="#">https://github.com/team2</a></span>
							</li>
							<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
								<h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter me-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
							<span class="text-secondary"><a href="#">https://twitter.com/team2</a></span>
							</li>
							<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
								<h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram me-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
							<span class="text-secondary"><a href="#">https://instragram.com/team2</a></span>
							</li>
							<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
								<h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook me-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
							<span class="text-secondary"><a href="#">https://facebook.com/team2</a></span>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-8">
				<div class="card">
					<div class="card-body">
						<div class="row mb-3">
							<div class="col-sm-3">
								<h6 class="mb-0">Full Name</h6>
							</div>
							<div class="col-sm-9 text-secondary">
							<input type="text" class="form-control-plaintext" value=@ViewBag.user.FirstName @ViewBag.user.LastName>
							</div>
						</div>
						<div class="row mb-3">
							<div class="col-sm-3">
								<h6 class="mb-0">Email</h6>
							</div>
							<div class="col-sm-9 text-secondary">
							<input type="text" class="form-control-plaintext" value=@ViewBag.user.Email>
							</div>
						</div>
						<div class="row mb-3">
							<div class="col-sm-3">
								<h6 class="mb-0">Phone</h6>
							</div>
							<div class="col-sm-9 text-secondary">
							<input type="text" class="form-control-plaintext" value=@ViewBag.user.PhoneNumber>
							</div>
						</div>
						<div class="row mb-3">
							<div class="col-sm-3">
								<h6 class="mb-0">Mobile</h6>
							</div>
							<div class="col-sm-9 text-secondary">
							<input type="text" class="form-control-plaintext" value=@ViewBag.user.PhoneNumber>
							</div>
						</div>
						<div class="row mb-3">
							<div class="col-sm-3">
								<h6 class="mb-0">Address</h6>
							</div>
							<div class="col-sm-9 text-secondary">
							
							<p class="form-control-plaintext">@ViewBag.user.Address</p>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-3"></div>
							<div class="col-sm-9 text-secondary">								
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">
						<div class="card">
							<div class="card-body">
								<h3>My CVs</h3>

							<table class="table table-success table-striped">
								<thead>
									<tr>
										<th scope="col">CV Name </th>
										<th scope="col">Show CV</th>
										<th scope="col">Edit</th>
										<th scope="col">Delete</th>
									</tr>
								</thead>

								<tbody class="table-group-divider">
									@foreach (var item in @ViewBag?.UserAllResume){
									<tr>
											<th scope="row">@item.ResumeName </th>
											<td><a class="btn btn-primary" href="https://localhost:7231/Users/Resume/ShowTemplateOne?tempId=@item.ResumeTemplteId" target="_blank" type="button">Show CV</a> </td>
											<td><a class="btn btn-secondary" href="https://localhost:7231/Users/Resume/EditResumeData?tempId=@item.ResumeTemplteId" target="_blank" type="button">Edit CV</a> </td>
											<td><a asp-area="Users" asp-controller="Resume" asp-action="DeleteResumeByTemplateId" asp-route-templateId="@item.ResumeTemplteId" class="btn btn-danger">Delete CV</a></td>
									</tr>
									}
							</table>
							<div class="card-body">
								<a asp-action="Index" class="btn btn-primary" asp-controller="CoverLetter">My Cover Letter</a>
							</div>

							<h5 class="d-flex align-items-center mb-3">Project Status</h5>
								<div class="progress mb-3" style="height: 5px">
									<div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
								</div>
								<p>Website Markup</p>
								<div class="progress mb-3" style="height: 5px">
									<div class="progress-bar bg-danger" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
								</div>
								<p>One Page</p>
								<div class="progress mb-3" style="height: 5px">
									<div class="progress-bar bg-success" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
								</div>
								<p>Mobile Template</p>
								<div class="progress mb-3" style="height: 5px">
									<div class="progress-bar bg-warning" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
								</div>
								<p>Backend API</p>
								<div class="progress" style="height: 5px">
									<div class="progress-bar bg-info" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
</div>