src/ResumeBuilderTeam2/CVBuilder.web/Areas/Admin/Controllers/ResumeTemplateController.cs
using Autofac;
using CVBuilder.Infrastructure.Exceptions;
using CVBuilder.Web.Areas.Admin.Models.ResumeTemplateModel;
using CVBuilder.Web.Models;
using CVBuilder.Web.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CVBuilder.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ResumeTemplateController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        ILifetimeScope _scope;
        ILogger<ResumeTemplateController> _logger;

        public ResumeTemplateController(ILifetimeScope scope, ILogger<ResumeTemplateController> logger, IWebHostEnvironment webHostEnvironment)
        {
            _scope = scope;
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var model = _scope.Resolve<ResumeTemplateListModel>();
            return View(model);
        }

        public IActionResult AddNewTemplate()
        {
            var model = _scope.Resolve<ResumeTemplateCreateModel>();
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult AddNewTemplate(ResumeTemplateCreateModel model)
        {
            model.ReturnUrl ??= Url.Content("~/");
            model.ResolveDependency(_scope);
            if (ModelState.IsValid)
            {
                try
                {
                    var folder = "Images/TemplatePicture/";
                    folder += "_" + model.TemplatePicture.FileName;
                    model.TemplatePictureUrl = "/" + folder;
                    var serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);
                    model.TemplatePicture.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

                   model.CreateResumeTemplate(model.TemplateName, model.TemplatePictureUrl);

                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = "Successfully added a new template",
                        Type = ResponseTypes.Success
                    });
                    return RedirectToAction("Index");
                }
                catch (DuplicateNameException ex)
                {
                    _logger.LogError(ex, ex.Message);
                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = ex.Message,
                        Type = ResponseTypes.Danger
                    });
                }
                catch (Exception e)
                {
                    _logger.LogError(e, "Server Error");
                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = "There was a problem in Adding new Template",
                        Type = ResponseTypes.Danger
                    });
                }
            }
            return View(model);

        }
        
        public IActionResult Update(int id)
        {
            var model = _scope.Resolve<ResumeTemplateUpdateModel>();
            model.Load(id);
            return View(model);
        }

        
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Update(ResumeTemplateUpdateModel model)
        {
            model.ResolveDependency(_scope);

            if (ModelState.IsValid)
            {
                try
                {
                    model.UpdateResumeTemplate();

                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = "Successfully updated course.",
                        Type = ResponseTypes.Success
                    });

                    return RedirectToAction("Index");
                }
                catch (DuplicateNameException ex)
                {
                    _logger.LogError(ex, ex.Message);

                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = ex.Message,
                        Type = ResponseTypes.Danger
                    });
                }
                catch (Exception e)
                {
                    _logger.LogError(e, "Server Error");

                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = "There was a problem in updating course.",
                        Type = ResponseTypes.Danger
                    });
                }
            }

            return View(model);
        }


        
        public IActionResult Delete(int id)
        {
            var model = _scope.Resolve<ResumeTemplateListModel>();

            if (ModelState.IsValid)
            {
                try
                {
                    model.DeleteTemplate(id);
                }
                catch (Exception e)
                {
                    _logger.LogError(e, "Server Error");
                }
            }

            return RedirectToAction("Index");
        }
    }
}

src/ResumeBuilderTeam2/CVBuilder.web/Areas/Users/Controllers/ResumeTemplateController.cs
using Microsoft.AspNetCore.Mvc;

namespace CVBuilder.Web.Areas.Users.Controllers
{
    [Area("Users")]
    public class ResumeTemplateController : Controller
    {
        public IActionResult Template1()
        {
            return View();
        }
    }
}

src/ResumeBuilderTeam2/CVBuilder.web/Areas/Admin/Views/ResumeTemplate/AddNewTemplate.cshtml
@model ResumeTemplateCreateModel
@{
    ViewData["Title"] = "AddNewTemplate";
}

<div class="container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-4">
            <!-- general form elements -->
            <div class="card card-primary p-2">
                <div class="card-header">
                    <h3 class="card-title">Add New Template</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form role="form" method="post" asp-area="Admin" asp-controller="ResumeTemplate" asp-action="AddNewTemplate"
                      enctype="multipart/form-data" asp-antiforgery="true">
                    <div class="card-body">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="TemplateName"></label>
                            <input type="text" class="form-control" asp-for="TemplateName" placeholder="Enter title">
                            <span asp-validation-for="TemplateName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="TemplatePicture" class="control-label"></label>
                            <div class="custom-file">
                                <input asp-for="TemplatePicture" class="custom-file-input" id="customFile" />
                                <label class="custom-file-label" for="customFile">Choose Template Picture</label>

                            </div>
                            <span asp-validation-for="TemplatePicture" class="text-danger"></span>
                        </div>

                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>

            </div>
            <!-- /.card -->

        </div>
        <!--/.col (left) -->
    </div>
    <!-- /.row -->
</div><!-- /.container-fluid -->
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script type="text/javascript">
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

src/ResumeBuilderTeam2/CVBuilder.web/Areas/Admin/Views/ResumeTemplate/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

src/ResumeBuilderTeam2/CVBuilder.web/Areas/Admin/Views/ResumeTemplate/Index.cshtml
@model ResumeTemplateListModel
@{
    ViewData["Title"] = "Index";
}

@section styles{
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
}

<div class="container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-12">
            <!-- general form elements -->
            <div class="card card-primary p-2 m-2">
                <div class="card-header mb-2">
                    <h3 class="card-title">List Of Templates</h3>
                </div>
                <!-- /.card-header -->
                <!-- Table start -->

                <table id="myTable" class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Template Name</th>
                            <th scope="col">Template Thumbnail Url</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var template in Model.GetResumeTemplates())
                        {
                            <tr>
                                <td>@template.Id</td>
                                <td>@template.TemplateName</td>
                                <td>@template.TemplateThumbNailUrl</td>
                                <td>
                                    <form method="post" asp-action="Delete" asp-controller="ResumeTemplate" asp-area="admin">
                                        <input type="hidden" name="id" value="@template.Id" />
                                        <button type="submit" class="btn btn-danger btn-sm show-bs-modal">
                                            <i class="fas fa-trash"></i> Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card -->
            <a class="btn btn-primary m-2 p-2" style="width:auto" asp-area="admin" asp-action="AddNewTemplate" asp-controller="ResumeTemplate">Add new Template</a>
        </div>
        <!--/.col (left) -->
    </div>
    <!-- /.row -->
</div>

@section Scripts{
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
    <!-- For CRUD PopUp -->
    <script src="~/js/modalnotification.js"></script>
}